[package]
name = "wasmer-marching-cubes"
version = "0.1.0"
authors = ["Will Usher <willusher.life@gmail.com>"]
edition = "2018"

[dependencies]
wasmer-runtime = "0.8.0"
wasmer = "0.1.0"
#cfg-if = "0.1"
wasm-bindgen = "0.2"
js-sys = "0.3"

