[package]
name = "marching-cubes"
version = "0.1.0"
authors = ["Will Usher <will@willusher.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
#cfg-if = "0.1"
#wasm-bindgen = "0.2"
#js-sys = "0.3"

[profile.release]
lto = true
opt-level = 3

